2021-06-03 14:43:12,231 - ERROR -  - base - _safe_close_cursor - 1869 - sqlalchemy.pool.impl.QueuePool - [MainProcess - 29896] - [Thread-1 - 27788] - Error closing cursor -   
Traceback (most recent call last):
  File "C:\Users\ASaxena\.virtualenvs\AIUEngine-gDpzpf_f\lib\site-packages\sqlalchemy\engine\base.py", line 1771, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\ASaxena\.virtualenvs\AIUEngine-gDpzpf_f\lib\site-packages\sqlalchemy\engine\default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
cx_Oracle.DatabaseError: DPI-1080: connection was closed by ORA-3113

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ASaxena\.virtualenvs\AIUEngine-gDpzpf_f\lib\site-packages\sqlalchemy\engine\base.py", line 1865, in _safe_close_cursor
    cursor.close()
cx_Oracle.DatabaseError: DPI-1010: not connected
2021-06-08 06:29:44,094 - ERROR -  - kafka_consumers - making_consumer_up -  210 - CCM.app_scope_methods.kafka_consumers - [MainProcess - 17892] - [Thread-3 - 26468] - __init__() missing 1 required positional argument: 'control_params_dict' -   
Traceback (most recent call last):
  File "C:\Users\ASaxena\PycharmProjects\AIUEngine\CCM\app_scope_methods\kafka_consumers.py", line 188, in making_consumer_up
    control_processing.delegator(topic_id, appln_cntxt, message=message_dict)  # as apart from 1st other are keyword args
  File "C:\Users\ASaxena\PycharmProjects\AIUEngine\CCM\app_scope_methods\control_processing.py", line 41, in delegator
    , 'CONTROL_ID': "TFA02_IFA19"})
TypeError: __init__() missing 1 required positional argument: 'control_params_dict'
2021-06-08 06:32:47,988 - ERROR -  - kafka_consumers - making_consumer_up -  210 - CCM.app_scope_methods.kafka_consumers - [MainProcess - 10220] - [Thread-12 - 26764] - __init__() missing 1 required positional argument: 'control_params_dict' -   
Traceback (most recent call last):
  File "C:\Users\ASaxena\PycharmProjects\AIUEngine\CCM\app_scope_methods\kafka_consumers.py", line 188, in making_consumer_up
    control_processing.delegator(topic_id, appln_cntxt, message=message_dict)  # as apart from 1st other are keyword args
  File "C:\Users\ASaxena\PycharmProjects\AIUEngine\CCM\app_scope_methods\control_processing.py", line 41, in delegator
    , 'CONTROL_ID': "TFA02_IFA19"})
TypeError: __init__() missing 1 required positional argument: 'control_params_dict'
2021-06-08 06:35:12,328 - ERROR -  - kafka_consumers - making_consumer_up -  210 - CCM.app_scope_methods.kafka_consumers - [MainProcess - 2700] - [Thread-3 - 3488] - 'StageProcessor' object is not callable -   
Traceback (most recent call last):
  File "C:\Users\ASaxena\PycharmProjects\AIUEngine\CCM\app_scope_methods\kafka_consumers.py", line 188, in making_consumer_up
    control_processing.delegator(topic_id, appln_cntxt, message=message_dict)  # as apart from 1st other are keyword args
  File "C:\Users\ASaxena\PycharmProjects\AIUEngine\CCM\app_scope_methods\control_processing.py", line 43, in delegator
    flwchart.execute_pipeline()
  File "C:\Users\ASaxena\PycharmProjects\AIUEngine\CCM\app_scope_methods\control_processing.py", line 333, in execute_pipeline
    bool_op_current_stage = self.current_stage_processor()
TypeError: 'StageProcessor' object is not callable
2021-06-08 06:37:01,824 - ERROR -  - kafka_consumers - making_consumer_up -  210 - CCM.app_scope_methods.kafka_consumers - [MainProcess - 10220] - [Thread-24 - 19104] - __init__() missing 1 required positional argument: 'control_params_dict' -   
Traceback (most recent call last):
  File "C:\Users\ASaxena\PycharmProjects\AIUEngine\CCM\app_scope_methods\kafka_consumers.py", line 188, in making_consumer_up
    control_processing.delegator(topic_id, appln_cntxt, message=message_dict)  # as apart from 1st other are keyword args
  File "C:\Users\ASaxena\PycharmProjects\AIUEngine\CCM\app_scope_methods\control_processing.py", line 41, in delegator
    , 'CONTROL_ID': "TFA02_IFA19"})
TypeError: __init__() missing 1 required positional argument: 'control_params_dict'
2021-06-08 06:39:26,265 - ERROR -  - kafka_consumers - making_consumer_up -  210 - CCM.app_scope_methods.kafka_consumers - [MainProcess - 18752] - [Thread-3 - 4900] - __init__() got an unexpected keyword argument 'message' -   
Traceback (most recent call last):
  File "C:\Users\ASaxena\PycharmProjects\AIUEngine\CCM\app_scope_methods\kafka_consumers.py", line 188, in making_consumer_up
    control_processing.delegator(topic_id, appln_cntxt, message=message_dict)  # as apart from 1st other are keyword args
  File "C:\Users\ASaxena\PycharmProjects\AIUEngine\CCM\app_scope_methods\control_processing.py", line 43, in delegator
    flwchart = ControlLifecycleFlowchart(control_id, appln_cntxt, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'message'
2021-06-08 06:42:16,128 - ERROR -  - control_processing - execute_current_stage_processor -  304 - CCM.app_scope_methods.control_processing - [MainProcess - 16300] - [Thread-5 - 21052] -  Error as method_TFA02_IFA19() takes 1 positional argument but 2 were given encountered for the stage STAGE1  process the control TFA02_IFA19 with input params  {'message': {'ID': 12, 'CONTROL_ID': 'TFA02_IFA19'}}  -   
Traceback (most recent call last):
  File "C:\Users\ASaxena\PycharmProjects\AIUEngine\CCM\app_scope_methods\control_processing.py", line 290, in execute_current_stage_processor
    result_frm_method_called = getattr(imprt_module, current_stage_processor_method_name)(self.appln, self.control_params_dict)
TypeError: method_TFA02_IFA19() takes 1 positional argument but 2 were given
2021-06-08 06:53:40,550 - ERROR -  - control_processing - execute_current_stage_processor -  304 - CCM.app_scope_methods.control_processing - [MainProcess - 23900] - [Thread-3 - 26148] -  Error as invalid syntax (control_TFA02_IFA19.py, line 15) encountered for the stage STAGE1  process the control TFA02_IFA19 with input params  {'message': {'ID': 13, 'CONTROL_ID': 'TFA02_IFA19'}}  -   
Traceback (most recent call last):
  File "C:\Users\ASaxena\PycharmProjects\AIUEngine\CCM\app_scope_methods\control_processing.py", line 280, in execute_current_stage_processor
    imprt_module = importlib.import_module(current_stage_processor_path_to_module)
  File "c:\users\asaxena\appdata\local\programs\python\python36-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "C:\Users\ASaxena\PycharmProjects\AIUEngine\CCM\app_scope_methods\control_logic_library\control_TFA02_IFA19.py", line 15
    passed_dict =**control_params_dict
                  ^
SyntaxError: invalid syntax
2021-06-08 06:53:40,603 - ERROR -  - control_processing - delegator -   65 - CCM.app_scope_methods.control_processing - [MainProcess - 23900] - [Thread-3 - 26148] -  Error encountered invalid syntax (control_TFA02_IFA19.py, line 15) -   
Traceback (most recent call last):
  File "C:\Users\ASaxena\PycharmProjects\AIUEngine\CCM\app_scope_methods\control_processing.py", line 58, in delegator
    imprt_module = importlib.import_module(item["path_to_module"])
  File "c:\users\asaxena\appdata\local\programs\python\python36-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "C:\Users\ASaxena\PycharmProjects\AIUEngine\CCM\app_scope_methods\control_logic_library\control_TFA02_IFA19.py", line 15
    passed_dict =**control_params_dict
                  ^
SyntaxError: invalid syntax
2021-06-08 06:56:02,387 - ERROR -  - control_processing - execute_current_stage_processor -  304 - CCM.app_scope_methods.control_processing - [MainProcess - 27096] - [Thread-7 - 9424] -  Error as  The method method_TFA02_IFA19 called outputted a NON Boolean output while processing the control TFA02_IFA19 in the stage STAGE1 for the input params {'message': {'ID': 14, 'CONTROL_ID': 'TFA02_IFA19'}} encountered for the stage STAGE1  process the control TFA02_IFA19 with input params  {'message': {'ID': 14, 'CONTROL_ID': 'TFA02_IFA19'}}  -   
Traceback (most recent call last):
  File "C:\Users\ASaxena\PycharmProjects\AIUEngine\CCM\app_scope_methods\control_processing.py", line 296, in execute_current_stage_processor
    raise Exception(f' The method {current_stage_processor_method_name} called outputted '
Exception:  The method method_TFA02_IFA19 called outputted a NON Boolean output while processing the control TFA02_IFA19 in the stage STAGE1 for the input params {'message': {'ID': 14, 'CONTROL_ID': 'TFA02_IFA19'}}
2021-06-08 06:56:02,390 - ERROR -  - control_processing - delegator -   65 - CCM.app_scope_methods.control_processing - [MainProcess - 27096] - [Thread-7 - 9424] -  Error encountered method_TFA02_IFA19() got an unexpected keyword argument 'message' -   
Traceback (most recent call last):
  File "C:\Users\ASaxena\PycharmProjects\AIUEngine\CCM\app_scope_methods\control_processing.py", line 62, in delegator
    result_frm_func_called = getattr(imprt_module, func_to_be_called)(appln_cntxt, **kwargs)
TypeError: method_TFA02_IFA19() got an unexpected keyword argument 'message'
